-- MySQL Script generated by MySQL Workbench
-- Sat Dec 22 13:48:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mynews
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mynews
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mynews` DEFAULT CHARACTER SET utf8 ;
USE `mynews` ;

-- -----------------------------------------------------
-- Table `mynews`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mynews`.`user` ;

CREATE TABLE IF NOT EXISTS `mynews`.`user` (
  `id` INT NOT NULL,
  `user_id` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(50) NULL,
  `push_yn` VARCHAR(1) NULL,
  `push_token` VARCHAR(255) NULL,
  `registered_date` DATETIME NOT NULL,
  `modified_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
